// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwjrrhluqiuchczgzzld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13anJyaGx1cWl1Y2hjemd6emxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjQ2NzUsImV4cCI6MjA2NjU0MDY3NX0.edj3Fr98TQJEeOalOntC4FUZgsrm0QvJXsf5Bz3zB9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);